[tool.semantic_release]
version_variable = "version.py:__version__"
# version_source = "tag"
version_source = "changelog"
branch = "main"
upload_to_pypi = false
upload_to_release = true  # ← This enables GitHub release uploads
changelog_file = "CHANGELOG.md"
build_command = ""


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
    "."
]