[tool.semantic_release]
version_variable = "version.py:__version__"
# version_source = "tag"
# version_source = "changelog"
version_source = ""
branch = "main"
upload_to_pypi = false
upload_to_release = true  # ← This enables GitHub release uploads
commit_version_number = true
commit_message = "chore(release): v{version} [skip ci]"
changelog_file = "CHANGELOG.md"
build_command = ""


[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
    "."
]